---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 3.1-slim

inputs:
- name: cf-deployment-concourse-tasks
- name: cf-deployment-concourse-tasks-latest-release
- name: release-version

outputs:
- name: release-notes-template

params:
  GH_ACCESS_TOKEN: ~

run:
  path: cf-deployment-concourse-tasks/ci/tasks/cf-decota-release-notes-template/task
