#!/bin/bash
set -exu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

pushd $SCRIPT_DIR
  PARSED_BUNDLE_VERSION=$(sed -n '/BUNDLED WITH/{;n;p;}' Gemfile.lock)
  gem uninstall bundler
  gem install bundler --version "$PARSED_BUNDLE_VERSION"
  bundle install --without development
popd

BUNDLE_GEMFILE=$SCRIPT_DIR/Gemfile \
  bundle exec ruby $SCRIPT_DIR/task.rb
