#!/bin/bash
set -exu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function check_delete_deployment_params() {
  if [ -z "$DEPLOYMENT_NAME" ]; then
    echo "DEPLOYMENT_NAME has not been set"
    exit 1
  fi
}

function bosh_delete_deployment() {
  local force_flag=""

  if [ "$IGNORE_ERRORS" = true ]; then
    force_flag="--force"
  fi

  bosh \
    -n \
    delete-deployment -d ${DEPLOYMENT_NAME} \
    ${force_flag}
}

function main() {
  check_delete_deployment_params
  setup_bosh_env_vars
  bosh_delete_deployment
}

main
