#!/bin/bash -exu

if [ -z "${SYSTEM_DOMAIN}" ]; then
  echo "\$SYSTEM_DOMAIN is a required parameter"
  exit 1
fi

function set_diego_docker() {
  if ${DIEGO_DOCKER}; then
    cf enable-feature-flag diego_docker
  else
    cf disable-feature-flag diego_docker
  fi
}

function set_task_creation() {
  if ${TASK_CREATION}; then
    cf enable-feature-flag task_creation
  else
    cf disable-feature-flag task_creation
  fi
}

function cf_login() {
  set +x
  echo "Authenticating as admin"
  cf auth admin $(bosh interpolate vars-store/${VARS_STORE_FILE} --path=/cf_admin_password)
  set -x
}

function main() {
  cf api --skip-ssl-validation "api.${SYSTEM_DOMAIN}"

  cf_login

  set_diego_docker
  set_task_creation

  cf feature-flags
}

main
