#!/bin/bash -eux

check_bbl_input_params() {
  set +x
  # Checks that we have IaaS credentials for either GCP or AWS
  if [ ! -z "${BBL_GCP_SERVICE_ACCOUNT_KEY}" ] || [ ! -z "${BBL_AWS_ACCESS_KEY_ID}" -a ! -z "${BBL_AWS_SECRET_ACCESS_KEY}" ]; then
    return 0
  else
    echo 'The BBL task must be configured with IaaS credentials. Please configure either `BBL_GCP_SERVICE_ACCOUNT_KEY`, or the `BBL_AWS_ACCESS_KEY_ID` `BBL_AWS_SECRET_ACCESS_KEY` pair.'
    exit 1
  fi
  set -x
}

function check_input_params() {
  set +x
  if [ -z "$MANIFEST_FILE" ]; then
    echo "MANIFEST_FILE has not been set"
    exit 1
  fi

  if [ -z "$VARS_STORE_FILE" ]; then
    echo "VARS_STORE_FILE has not been set"
    exit 1
  fi

  if [ -z "$SYSTEM_DOMAIN" ]; then
    echo "SYSTEM_DOMAIN has not been set"
    exit 1
  fi

  if ${FAIL_ON_DOWNTIME}; then
    if [ -z "${DEPLOY_WITH_UPTIME_MEASUREMENTS}" ]; then
      echo "FAIL_ON_DOWNTIME requires that DEPLOY_WITH_UPTIME_MEASUREMENTS be true. Exiting."
      exit 1
    fi
  fi
  set -x
}

function commit_bbl_state_dir {
  local root_dir
  root_dir="${1}"
  local commit_message
  commit_message="${2}"

  pushd "${root_dir}/bbl-state/${BBL_STATE_DIR}"
    if [[ -n $(git status --porcelain) ]]; then
      set_git_config
      git add --all .
      git commit -m "${commit_message}"
    fi
  popd

  pushd "${root_dir}"
    shopt -s dotglob
    cp -R "bbl-state/." "updated-bbl-state/"
  popd
}

function set_git_config() {
  if [ -z "${GIT_COMMIT_USERNAME}" ]; then
    GIT_COMMIT_USERNAME="CI Bot"
  fi

  if [ -z "${GIT_COMMIT_EMAIL}" ]; then
    GIT_COMMIT_EMAIL="cf-release-integration@pivotal.io"
  fi

  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"
}

function commit_vars_store() {
  pushd vars-store
    if [[ -n $(git status --porcelain) ]]; then
      set_git_config
      git add "${VARS_STORE_FILE}"
      git commit -m "Update vars-store after deploy"
    fi
  popd

  shopt -s dotglob
  cp -R vars-store/* updated-vars-store/
}

function setup_bosh_env_vars() {
  local stealth_mode=true

  if [[ "$-" == *x* ]]; then
    stealth_mode=false
  fi

  if [ ${stealth_mode} == false ]; then
    set +ux
  else
    set +u
  fi

  pushd "bbl-state/${BBL_STATE_DIR}"
    eval "$(bbl print-env)"
  popd

  if [ "${steath_mode}" == false ]; then
    set -ux
  else
    set -u
  fi
}

function bosh_interpolate() {
  set +u
  local root_dir
  root_dir="${1}"

  local release_name
  release_name="${2}"
  set -u

  local bosh_manifest
  bosh_manifest="cf-deployment/${MANIFEST_FILE}"

  local arguments
  if ${USE_VARS_STORE}; then
    arguments="--vars-store vars-store/${VARS_STORE_FILE} -v system_domain=${SYSTEM_DOMAIN}"
  else
    arguments="-v system_domain=${SYSTEM_DOMAIN}"
  fi

  for op in ${OPS_FILES}
  do
    arguments="${arguments} -o ops-files/${op}"
  done

  for vf in ${VARS_FILES}
  do
    arguments="${arguments} -l vars-files/${vf}"
  done

  if [ -n "${release_name}" ]; then
    cat << EOF > create-provided-release.yml
---
- type: replace
  path: /releases/name=${release_name}
  value:
    name: ${release_name}
    version: create
    url: file://${root_dir}/release
EOF
    arguments="${arguments} -o create-provided-release.yml"
  fi

  INTERPOLATED_MANIFEST=$(mktemp)
  export INTERPOLATED_MANIFEST

  # We are intentionally passing a series of arguments here:
  # shellcheck disable=SC2086
  local bosh_arguments
  bosh_arguments=""
  if ${USE_VARS_STORE}; then
    bosh_arguments="--var-errs"
  fi

  bosh \
    -n \
    interpolate ${arguments} \
    ${bosh_arguments} \
    "${bosh_manifest}" \
    > "${INTERPOLATED_MANIFEST}"
}

write_uptimer_deploy_config() {
  local deployment_name
  deployment_name=${1}

  local manifest
  manifest=${2}

  # Give bogus values for TCP_DOMAIN and AVAILABLE_PORT
  # so that we don't have to do jq magic.
  if [ -z "${TCP_DOMAIN}" ]; then
    TCP_DOMAIN=" "
  fi
  if [ -z "${AVAILABLE_PORT}" ]; then
    AVAILABLE_PORT="-1"
  fi

  set +x
  echo '{}' | jq --arg cf_api api.${SYSTEM_DOMAIN} \
    --arg admin_password $(bosh int --path=/cf_admin_password vars-store/"${VARS_STORE_FILE}") \
    --arg app_domain ${SYSTEM_DOMAIN} \
    --arg manifest $manifest \
    --arg deployment_name $deployment_name \
    --arg run_app_syslog_availability ${MEASURE_SYSLOG_AVAILABILITY} \
    --arg tcp_domain "${TCP_DOMAIN}" \
    --arg available_port ${AVAILABLE_PORT} \
    --arg app_pushability ${APP_PUSHABILITY_THRESHOLD} \
    --arg http_availability ${HTTP_AVAILABILITY_THRESHOLD} \
    --arg recent_logs ${RECENT_LOGS_THRESHOLD} \
    --arg streaming_logs ${STREAMING_LOGS_THRESHOLD} \
    --arg app_syslog_availability ${APP_SYSLOG_AVAILABILITY_THRESHOLD} \
    '{
      "while": [{
        "command":"bosh",
        "command_args":["--tty", "-n", "deploy", $manifest, "-d", $deployment_name]
      }],
      "cf": {
        "api": $cf_api,
        "app_domain": $app_domain,
        "admin_user": "admin",
        "admin_password": $admin_password,
        "tcp_domain": $tcp_domain,
        "available_port": $available_port | tonumber
      },
      "allowed_failures": {
        "app_pushability": $app_pushability | tonumber,
        "http_availability": $http_availability | tonumber,
        "recent_logs": $recent_logs | tonumber,
        "streaming_logs": $streaming_logs | tonumber,
        "app_syslog_availability": $app_syslog_availability | tonumber
      },
      "optional_tests": {
        "run_app_syslog_availability": $run_app_syslog_availability | ascii_downcase | contains("true")
      }
    }'
  set -x
}

function uptimer_bosh_deploy() {
  if ${MEASURE_SYSLOG_AVAILABILITY}; then
    if [ -z "${TCP_DOMAIN}" ] || [ -z "${AVAILABLE_PORT}" ]; then
      echo "Both TCP_DOMAIN and AVAILABLE_PORT are required to run syslog availability measurement."
      exit 1
    fi
  fi

  local deployment_name
  deployment_name=$(bosh interpolate "${INTERPOLATED_MANIFEST}" --path /name)

  uptimer_config=$(mktemp)
  write_uptimer_deploy_config "${deployment_name}" "${INTERPOLATED_MANIFEST}" > ${uptimer_config}
  pushd cf-deployment > /dev/null
    set +e
    local exitStatus
    uptimer -configFile ${uptimer_config}
    exitStatus=$?
    set -e
  popd

  # exitStatus 64 means that there was downtime, but the deployment was successful
  if [ "${FAIL_ON_DOWNTIME}" = "false" ] && [ $exitStatus == 64 ]; then
    exit 0
  fi

  exit $exitStatus
}

function bosh_deploy() {
  local deployment_name
  deployment_name=$(bosh interpolate "${INTERPOLATED_MANIFEST}" --path /name)

  if ${DEPLOY_WITH_UPTIME_MEASUREMENTS}; then
    uptimer_bosh_deploy
  else
    pushd cf-deployment > /dev/null
      bosh \
        -n \
        -d "${deployment_name}" \
        deploy \
        "${INTERPOLATED_MANIFEST}"
    popd
  fi
}

function remove_vars_store() {
  rm -f vars-store/"${VARS_STORE_FILE}"
}

write_gcp_service_account_key() {
  set +x
  if [ -f "${BBL_GCP_SERVICE_ACCOUNT_KEY}" ]; then
    cp "${BBL_GCP_SERVICE_ACCOUNT_KEY}" /tmp/google_service_account.json
  else
    echo "${BBL_GCP_SERVICE_ACCOUNT_KEY}" > /tmp/google_service_account.json
  fi
  export BBL_GCP_SERVICE_ACCOUNT_KEY="/tmp/google_service_account.json"
  set -x
}

get_password_from_credhub() {
  set +x
  local bosh_manifest_password_variable_name=$1
  echo $(credhub find -j -n ${bosh_manifest_password_variable_name} | jq -r .credentials[].name | xargs credhub get -j -n | jq -r .value)
  set -x
}
