#!/bin/bash -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

optional_submodule_bump() {
  set +x
    if [ -z "${BUMP_SUBMODULE}" ] && ! [ -z "${SUBMODULE_BRANCH}" ]; then
      echo "SUBMODULE_BRANCH must not be set without a path set for BUMP_SUBMODULE"
      exit 1
    fi

    if [ -z "${SUBMODULE_BRANCH}" ] && ! [ -z "${BUMP_SUBMODULE}" ]; then
      echo "BUMP_SUBMODULE must not be set without a ref set for SUBMODULE_BRANCH"
      exit 1
    fi
  set -x

  if ! [ -z "${BUMP_SUBMODULE}" ]; then
    pushd "release/${BUMP_SUBMODULE}"
      git checkout "${SUBMODULE_BRANCH}"
      git pull
    popd
  fi
}

main() {
  local root_dir
  root_dir="${1}"

  check_input_params
  optional_submodule_bump
  setup_bosh_env_vars
  if ${REGENERATE_VARS_STORE}; then
    remove_vars_store
  fi
  bosh_interpolate "${root_dir}" "$(grep final_name release/config/final.yml | awk '{print $2}')"
  bosh_deploy
  close_bbl_ssh_connection
}

trap commit_vars_store EXIT

main "${PWD}"
