#!/bin/bash -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function main() {
  local root_dir
  root_dir="${1}"

  check_input_params
  setup_bosh_env_vars
  if ${REGENERATE_VARS_STORE}; then
    remove_vars_store
  fi
  bosh_interpolate "${root_dir}" "$(grep final_name release/config/final.yml | awk '{print $2}')"
  bosh_deploy
}

trap commit_vars_store EXIT

main "${PWD}"
