#!/bin/bash -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function main() {
  check_input_params
  setup_bosh_env_vars
  bosh_interpolate
  if [ "$REGENERATE_CREDENTIALS" == true ]; then
    remove_credentials_from_credhub
  fi
  bosh_update_dns_runtime_config
  upload_stemcells
  # shellcheck disable=SC2086
  bosh_deploy ${BOSH_DEPLOY_ARGS}
}

main
