#!/bin/bash -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

optional_submodule_bump() {
  set +x
    if [ -z "${BUMP_SUBMODULE}" ] && ! [ -z "${SUBMODULE_BRANCH}" ]; then
      echo "SUBMODULE_BRANCH must not be set without a path set for BUMP_SUBMODULE"
      exit 1
    fi

    if [ -z "${SUBMODULE_BRANCH}" ] && ! [ -z "${BUMP_SUBMODULE}" ]; then
      echo "BUMP_SUBMODULE must not be set without a ref set for SUBMODULE_BRANCH"
      exit 1
    fi
  set -x

  if ! [ -z "${BUMP_SUBMODULE}" ]; then
    pushd "release/${BUMP_SUBMODULE}"
      git checkout "${SUBMODULE_BRANCH}"
      git pull
    popd
  fi
}

main() {
  local root_dir
  root_dir="${1}"

  export USE_VARS_STORE="false"

  check_input_params
  optional_submodule_bump
  setup_bosh_env_vars
  bosh_interpolate "${root_dir}" "$(grep final_name release/config/final.yml | awk '{print $2}')"
  if [ "$REGENERATE_CREDENTIALS" == true ]; then
    remove_credentials_from_credhub
  fi
  bosh_deploy
}

main "${PWD}"
