#!/bin/bash -exu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function check_input_params() {
  if [ -z "$DEPLOYMENT_NAME" ]; then
    echo "DEPLOYMENT_NAME has not been set"
    exit 1
  fi
  if [ -z "$ERRAND_NAME" ]; then
    echo "ERRAND_NAME has not been set"
    exit 1
  fi
}

function main() {
  check_input_params
  setup_bosh_env_vars

  PARAMS=""

  if [ "$KEEP_ALIVE" = true ]; then
    PARAMS="$PARAMS --keep-alive"
  fi

  if [ -n "${INSTANCE}" ]; then
    PARAMS="${PARAMS} --instance=${INSTANCE}"
  fi

  bosh -d "${DEPLOYMENT_NAME}" run-errand "${ERRAND_NAME}" ${PARAMS}
}

main
