#!/bin/bash
set -exu

source cf-deployment-concourse-tasks/shared-functions

function bosh_delete_loggregator() {
  bosh -n delete-release loggregator
}

function main() {
  setup_bosh_env_vars
  bosh_delete_loggregator
}

main
