#!/bin/bash
set -exu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function bosh_clean_up() {
  if [ -z "${CLEAN_ALL}" ] || [ "${CLEAN_ALL}" = true ]; then
    bosh -n clean-up --all
  else
    bosh -n clean-up
  fi
}

function main() {
  setup_bosh_env_vars
  bosh_clean_up
}

trap close_bbl_ssh_connection EXIT

main
