#!/bin/bash
set -exu

function setup_bosh_env_vars() {
  set +x
  pushd "bbl-state/${BBL_STATE_DIR}"
    export BOSH_CA_CERT="$(bbl director-ca-cert)"
    export BOSH_ENVIRONMENT=$(bbl director-address)
    export BOSH_CLIENT=$(bbl director-username)
    export BOSH_CLIENT_SECRET=$(bbl director-password)
  popd
  set -x
}

function bosh_clean_up() {
  if [ -z "${CLEAN_ALL}" ] || [ "${CLEAN_ALL}" = true ]; then
    bosh -n clean-up --all
  else
    bosh -n clean-up
  fi
}

function main() {
  setup_bosh_env_vars
  bosh_clean_up
}

main
