#!/bin/bash
set -exu

function setup_bosh_env_vars() {
  set +x
  pushd "bbl-state/${BBL_STATE_DIR}"
    eval "$(bbl print-env)"
  popd
  set -x
}

function bosh_clean_up() {
  if [ -z "${CLEAN_ALL}" ] || [ "${CLEAN_ALL}" = true ]; then
    bosh -n clean-up --all
  else
    bosh -n clean-up
  fi
}

function main() {
  setup_bosh_env_vars
  bosh_clean_up
}

main
