#!/bin/bash -exu

create_tracker_request_body() {
  BBL_VERSION=$(cat bbl-github-release/version)

  cat << EOF
{
  "name": "New bbl version: ${BBL_VERSION} is available",
  "story_type": "chore"
}
EOF
}

set +x


main() {
  echo "$(create_tracker_request_body)"

  curl -f \
    -H "X-TrackerToken: ${TRACKER_API_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "$(create_tracker_request_body)" \
    "https://www.pivotaltracker.com/services/v5/projects/${TRACKER_PROJECT_ID}/stories"
}

main
