#!/bin/bash -e

check_params() {
  if [ ! -d ${ROOT_DIR}/base-ops-files/${BASE_OPS_FILE_DIR} ]; then
    echo "[ERROR] base-ops-files/${BASE_OPS_FILE_DIR} must exist in order to collect operations files."
    exit 1
  fi

  if [ ! -z "${NEW_OPS_FILES}" ]; then
    for OPERATION in ${NEW_OPS_FILES}; do
      if [ ! -e "${ROOT_DIR}/new-ops-files/${OPERATION}" ]; then
        echo "[ERROR] All files specified in NEW_OPS_FILES must exist.  [ new-ops-files/${OPERATION} ] does not."
        exit 1
      fi
    done
  fi
}

# Create collection directory (task output)
create_collection_directory() {
  if [ ! -d ${ROOT_DIR}/collected-ops-files ]; then
    mkdir -p ${ROOT_DIR}/collected-ops-files/${BASE_OPS_FILE_DIR}
  fi
}

set_collection_path() {
  if [ -z "${BASE_OPS_FILE_DIR}" ]; then
    COLLECTION_PATH="${ROOT_DIR}/collected-ops-files"
  else
    COLLECTION_PATH="${ROOT_DIR}/collected-ops-files/${BASE_OPS_FILE_DIR}"
  fi
}

# Copy all base operations to collection
collect_base_operations() {
  cp -r ${ROOT_DIR}/base-ops-files/${BASE_OPS_FILE_DIR}/ ${ROOT_DIR}/collected-ops-files
}

# Copy each new operation to collection
collect_new_operations() {
  if [ -z "${NEW_OPS_FILES}" ]; then
    # If we don't have a list of specific ops files to collect, then collect
    # all of the files at the root
    find ${ROOT_DIR}/new-ops-files -type f -maxdepth 1 | xargs -n1 -I{} cp {} ${COLLECTION_PATH}
  else
    # ... otherwise, add them one by one
    for OPERATION in ${NEW_OPS_FILES}; do
      # Get only the filename part of the specified ops file since we're putting all of them in
      # the same "collected" directory
      local target_filename
      target_filename=$(basename "${OPERATION}")

      cp ${ROOT_DIR}/new-ops-files/${OPERATION} ${COLLECTION_PATH}/${target_filename}
    done
  fi
}

main() {
  ROOT_DIR="${1}"

  check_params
  create_collection_directory
  set_collection_path
  collect_base_operations
  collect_new_operations
}

main ${PWD}
