#!/bin/bash
set -xeu

build_dir=${PWD}

export CONFIG
CONFIG=$(mktemp)

original_config="${build_dir}/integration-config/${CONFIG_FILE_PATH}"
reporter_config="${build_dir}/integration-config/${REPORTER_CONFIG_FILE_PATH}"

if ${CAPTURE_LOGS}; then
  jq ".artifacts_directory=\"${build_dir}/cats-trace-output\"" ${original_config} > ${CONFIG}
else
  cp ${original_config} ${CONFIG}
fi

if [ -f ${reporter_config} ]; then
  echo "Configuring Honeycomb integration..."
  set +x
  reporter_config_value="$(cat ${reporter_config})"
  combined_config_value="$(cat ${CONFIG} | jq --argjson reporter "$reporter_config_value" '. + $reporter')"

  pushd "${build_dir}/cf-acceptance-tests"
    combined_config_value="$(echo ${combined_config_value} | jq ".reporter_config.custom_tags.cats_git_sha=\"$(git rev-parse HEAD)\"" )"
    combined_config_value="$(echo ${combined_config_value} | jq ".reporter_config.custom_tags.cf_cli_version=\"$(cf -v | awk '{print $3}')\"" )"
  popd

  echo "$combined_config_value" > ${CONFIG}
  set -x
fi

CF_GOPATH=/go/src/github.com/cloudfoundry/

echo "Moving cf-acceptance-tests onto the gopath..."
mkdir -p $CF_GOPATH
cp -R cf-acceptance-tests $CF_GOPATH

cd /go/src/github.com/cloudfoundry/cf-acceptance-tests

export CF_DIAL_TIMEOUT=11

export CF_PLUGIN_HOME=$HOME

./bin/test \
-keepGoing \
-randomizeAllSpecs \
-skipPackage=helpers \
-slowSpecThreshold=120 \
-nodes="${NODES}" \
-skip="${SKIP_REGEXP}" \
-flakeAttempts=${FLAKE_ATTEMPTS} \
-noisySkippings=false
#! flakeAttempts re-added 9/15 to mitigate reliability issues with Load Balancer 502s.
#! This is a temporary measure, and should be removed
#! as soon as the 502 issues are resolved or mitigated some other way.
