#!/bin/bash -xeu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function main() {
  local root_dir
  root_dir="${1}"

  check_bbl_input_params

  pushd "bbl-state/${BBL_STATE_DIR}"
    local bbl_iaas
    bbl_iaas=$(jq -r .iaas bbl-state.json)

    if [ "${bbl_iaas}" == "gcp" ]; then
      pushd "${root_dir}/bbl-state"
        write_gcp_service_account_key
      popd
    fi

    bbl \
      --debug \
      destroy \
      --no-confirm \
      --skip-if-missing > "${root_dir}"/bbl_destroy.txt
  popd
}

trap "commit_bbl_state_dir ${PWD} 'Remove bbl state dir'" EXIT

main ${PWD}
