#!/bin/bash -xeu

function commit_bbl_state_file {
  local root_dir
  root_dir="${1}"

  pushd "${root_dir}/bbl-state"
    if [[ -n $(git status --porcelain) ]]; then
      git config user.name "CI Bot"
      git config user.email "cf-release-integration@pivotal.io"
      git add --all bbl-state.json
      git commit -m "Remove bbl-state.json"
    fi
  popd

  pushd "${root_dir}"
    shopt -s dotglob
    cp -R bbl-state/* updated-bbl-state/
  popd
}

function main() {
  pushd bbl-state
    bbl \
      destroy \
      --no-confirm \
      --skip-if-missing
  popd
}

trap "commit_bbl_state_file ${PWD}" EXIT

main
